### ISSUE TITLE
Daisy in VirtualBox Failed to Reboot with new Linux Kernel

### ISSUE THREAD

**Issue by Meditator-hkx** [DDST-NVM/Daisy#2]
I use Ubuntu 14.04 in VirtualBox.

All the commands for building new kernel follow the rules in GuideBook.
But when I typed "reboot" and choose Linux kernel 3.12.49.
The system stopped at:
 " 载入Linux 3.12.49 ... 
   载入初始化内存盘 ...
"
I just don't understand what is wrong with our program.
Maybe I should install a real Ubuntu environment and remake the process.
I'll write something later.

**Comment by Menooker** [comment]
Make sure the memory size of the VM is larger than the minimum required size for the modified kernel. What' s the configuration of the VM?

在 2017年3月2日，19:11，Kaixin Huang <notifications@github.com<mailto:notifications@github.com>> 写道：


I use Ubuntu 14.04 in VirtualBox.

All the commands for building new kernel follow the rules in GuideBook.
But when I typed "reboot" and choose Linux kernel 3.12.49.
The system stopped at:
" 载入Linux 3.12.49 ...
载入初始化内存盘 ...
"
I just don't understand what is wrong with our program.
Maybe I should install a real Ubuntu environment and remake the process.
I'll write something later.

**Comment by Meditator-hkx** [comment]
A new problems seems to be related with Video Card Configuration.
The window is vague when booting with Linux kernel 3.12.49.
Waiting to see if it can boot successfully...

**Comment by Meditator-hkx** [comment]
I can run ptest now.
The problems are concluded as below:

1. The memory size should be set more than 6GB, otherwise it cannot boot successfully. A Virtual Machine is not recommended.

2. If in the boot phase, the window becomes vague, then we should edit the grub interface (reference: http://ihyperwin.iteye.com/blog/1871458).

3. Enter the recovery mode and Ubuntu with linux-3.12.49 will boot successfully.

4. May need chmod command to run create_so.sh.
